### ISSUE TITLE
Why does the website require such aggressive permissions?

### ISSUE THREAD

**Issue by NullVoxPopuli** [rcbuild-info/website#17]
This application will be able to read and write all public repository data. This includes the following:

Code
Issues
Pull requests
Wikis
Settings
Webhooks and services
Deploy keys

It shouldn't need to create issues / pull request / anything on any of my repositories...

**Comment by tannewt** [comment]
That is the finest grain of permissions that I could ask for. My site actually stores all of your info in a public repo of the user's called rcbuild.info-builds (mine is here: https://github.com/tannewt/rcbuild.info-builds ) No other repos are touched. This has the benefit of version all data changes and providing anyone access to the data. It also means I don't host any of it myself. Issue #7 is filed for me to more clearly explain that in the login flow.

**Comment by NullVoxPopuli** [comment]
interesting -- but if someone were to get access to your oauth tokens, we could be in trouble? You are using https, so that's good. :-)

looking at these: https://developer.github.com/v3/oauth/#scopes, it looks like public_repo is what you're using?
hmm. I wish github had more options.

**Comment by tannewt** [comment]
Yup, oauth tokens are stored by your browser encrypted by me. https://github.com/rcbuild-info/website/blob/master/application.py#L486 Your login name is not encrypted but its all https.

Webhooks are used to update the build index and are signed with a separate key for each user so only you can spoof you.

public_repo is exactly the scope I'm requesting. I wish it was finer grained too. I wish I could say I want to create a fork and then only have access to it.

**Comment by NullVoxPopuli** [comment]
oh! well, if they aren't stored centralizedily anywhere, I feel much more comfortable about all this. woo

**Comment by tannewt** [comment]
Great! I'm trying to store as little as possible. :-) Let me know any other feedback you have.

**Comment by NullVoxPopuli** [comment]
in other news, all these auto complete fields are amazing

**Comment by tannewt** [comment]
Glad you like them! They've gotten kinda slow with all of the parts I added.

**Comment by btreecat** [comment]
How did you implement them?

**Comment by tannewt** [comment]
React autosuggest all client-side for the build editor. (Yeah I know.) https://github.com/rcbuild-info/website/blob/master/src/components/part-entry.jsx#L70

The search box is a React Typeahead also all client side. https://github.com/rcbuild-info/website/blob/master/src/components/build-list.jsx#L124
